#!/usr/bin/env bash
#Install nginx web server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
REDIRECT_CONF="server {
    listen 80;
    server_name _;
    root /var/www/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 https://www.tutorialspoint.com/sql/index.htm;
    }
}"
echo "$REDIRECT_CONF" > /etc/nginx/sites-available/default

sudo service nginx restart
