#!/usr/bin/env bash
#Install nginx web server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
REDIRECT_CONF="server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 http://example.com/; # Replace example.com with your target URL
    }
    location / {
        root /var/www/html;
        index index.html;
    }
}"
echo "$REDIRECT_CONF" > /etc/nginx/sites-available/default

sudo service nginx restart
