#!/usr/bin/env bash
#Install nginx web server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

REDIRECT_CONF="server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 https://www.tutorialspoint.com/sql/index.htm;
    }

    location / {
        root /var/www/html;
        index index.html;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

}"
echo "$REDIRECT_CONF" > /etc/nginx/sites-available/default

sudo service nginx restart
