#!/usr/bin/env bash
# Configure Nginx server with a custom 404 page that contains "Ceci n'est pas une page"

set -e

# Update package lists and install Nginx
echo "Installing Nginx..."
apt-get update
apt-get install -y nginx

ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

CUSTOM_404_CONF="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;

    # Custom 404 error page
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}"
echo "$CUSTOM_404_CONF" > /etc/nginx/sites-available/default

nginx -s reload || service nginx restart
