#!/usr/bin/env bash
# Bash script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)


for file in *; do
    if [ -f "$file" ]; then
        name_after_dash="${file#*-}"
        
        if [ "$name_after_dash" != "$file" ]; then
            echo "$name_after_dash"
        else
            echo "$file"
        fi
    fi
done
